@isTest(SeeAllData=true)

    private class BigMachinesParameters_test 
    {

        static testMethod void bmtest() 
        {
         //BigMachinesParameters bmp = new BigMachinesParameters();
         BigMachinesParameters.usesSSL=false; 
         BigMachinesParameters.bm_site ='testcentrica1';
         BigMachinesParameters.username ='Qk1TRkRDSW50ZWdyYXRpb24=';
         BigMachinesParameters.password ='SW50ZWdyYXRlTWU='; 
         BigMachinesParameters.process_id ='4128545'; 
         BigMachinesParameters.action_id_copy ='4129928';
         BigMachinesParameters.action_id_open ='4129958'; 
         BigMachinesParameters.document_id ='4128610'; 
         BigMachinesParameters.process_var ='quotes_process_bmClone_43'; 
         
         
        }
        
     }