global class callBackResponse{    
        public String JobID;
        public String LeadID;
        public String quoteID;
        Public date callbackRequestDate;
        Public String callBackTime; 
        //Public String errorMessage;
        public list<String> errorList = new list<String>();
    
    /*public class Error
    {
      public String errorcode;
      public String errorMessage;
    }*/
}