public class DisplayMode 
{
	public Integer VIEW 		{ set; get{ return 1;}}
	public Integer EDIT   		{ set; get{ return 2;}}
	public Integer ADDRESSONLY  { set; get{ return 3;}}	
	public Integer STATUS  		{ set; get{ return 4;}}
	public Integer EXISTING  	{ set; get{ return 5;}}
	public Integer APPOINTSUCCESS 	{ set; get{ return 6;}}
	public Integer WRAPUPSCREENMODE	{ set; get{ return 7;}}
	public Integer APPOINTSUCCESSEXIST 	{ set; get{ return 8;}}
	
}