public class QueryFields {
    
    public final static list<string> postcodeSectorQuery_selectByNameAndType = new list<string>{
                                                                                                'Id',
                                                                                                'Name',
                                                                                                'Water_Hardness__c',
                                                                                                'Sub_Patch__c',
                                                                                                'Trading_Name__c',
                                                                                                'Country__c'
                                                                                                };

}